# Generated by Django 5.2.3 on 2025-06-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
