# Generated by Django 5.2.3 on 2025-06-30 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_color_size_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_color',
            field=models.CharField(default='M', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(default='Black', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='authapp.product'),
        ),
    ]
