# Generated by Django 5.2.3 on 2025-06-30 11:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_cart_selected_color_cart_selected_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product', 'selected_size', 'selected_color')},
        ),
    ]
